### DISCUSSION TITLE
Misaligned arrow when patching custom built iosevka

### DISCUSSION THREAD

**Discussion by leana8959** [ryanoasis/nerd-fonts#1519] [Q&A]
Hello,

I noticed that this "upload" glyph is not aligned. Could someone help me understand why?
The official patched version of iosevka doesn't have this issue.

<img width="217" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/87855546/649223c0-68bb-4250-889f-4f1beb3204a2">

I'm building my own iosevka using this build plan:

```toml
[buildPlans.hIosevka]
family = "hIosekva"
spacing = "normal"
serifs = "sans"

[buildPlans.hIosevka.ligations]
inherits = "haskell"
enables = [
    "brst",  # (* *)
    "logic", # \/ /\
    "lteq-separate", # <=
    "gteq-separate", # >=
]

[buildPlans.hIosevka.variants.design]
capital-z = 'straight-serifless-with-crossbar'
capital-q = 'crossing'
lower-lambda = 'tailed-turn'
seven = 'straight-serifless-crossbar'
number-sign = 'slanted'
ampersand = "upper-open"
dollar = 'open'
percent = 'rings-continuous-slash-also-connected'
```

And I used this script to patch all the files:
```bash
find \( -name \*.ttf -o -name \*.otf \) | parallel nerd-font-patcher {} \
    --name {/.}-NF \
    --complete \
    --quiet \
    --no-progressbars \
    --outputdir nerd-font
```
I have tried the `--use-single-width-glyphs`, it didn't make a difference.

Thank you for your time !
