### ISSUE TITLE
Chrome / Chrome OS support

### ISSUE THREAD

**Issue by jokerkeny** [ryanoasis/nerd-fonts#345]
#### 🎯 Subject of the issue
Could you add Chrome / Chrome OS support by creating web fonts version like [powerline-web-fonts](https://github.com/wernight/powerline-web-fonts)?

#### 🔧 Your Setup

Font: Droid Sans Mono Nerd Font
Terminal: [Secure Shell App](https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo)
OS: Chrome OS and Chrome Web Browser on Windows

#### Screenshot
![image](https://user-images.githubusercontent.com/10593391/55705965-04218d00-59ae-11e9-8372-fc6761e8cdb9.png)

**Comment by ryanoasis** [comment]
This would be useful and it seems doable

**Comment by ryanoasis** [comment]
This would be creating `woff` and `woff2` versions of the fonts. I did create these for the symbols only font but not the all the fonts

**Comment by wrightb4u** [comment]
This would be super helpful. Currently using ChromeOS as well. Having the same problem with native terminal and Hyper.js terminal. However, Gnome Terminal works because it doesn't have to use web fonts for this. Would love to know if there is any progress on this :)

**Comment by vn7n24fzkq** [comment]
Here is a simple solution.
 - Set a custom CSS(inline text) like this one.
 - Src is the font raw file where you can download .
```css
@font-face {
    font-family: "DejaVu Sans Mono Nerd";
    src: url("https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf");
    font-weight: normal;
    font-style: normal;
}
```
![image](https://user-images.githubusercontent.com/20241522/65017495-7f25a100-d959-11e9-9f38-915bc4c613a8.png)
![image](https://user-images.githubusercontent.com/20241522/65018313-60280e80-d95b-11e9-81b9-84b4afc9dd2d.png)
