### ISSUE TITLE
Monospace font rendering issues in Alacritty with 2.2.1 but not 2.1.0

### ISSUE THREAD

**Issue by liamtimms** [ryanoasis/nerd-fonts#896]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Major differences in font rendering for jetbrains between releases `2.1.0` and `2.2.1`.

Expected behavior:

I'd expect that spacing/rendering would continue working as in previous versions. 

Example symbols:

**left** window is with release `2.1.0` while **right** is `2.2.1`: 

![image](https://user-images.githubusercontent.com/14281621/187034258-bb835d3a-e872-420d-8eeb-3acb62a577cf.png)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

**font:**  ` family: jetbrainsmono medium nerd font `
**from:** [nerd-fonts-jetbrains-mono](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nerd-fonts-jetbrains-mono) via AUR
**terminal:** alacritty
**OS:** Arch Linux

#### ★ Screenshots (Optional)

**left** window is with release `2.1.0` while **right** is `2.2.1`: 

![image](https://user-images.githubusercontent.com/14281621/187034170-bda2eff8-a8a0-4c11-95ad-1e1f8def51cb.png)

Also of note: 

![image](https://user-images.githubusercontent.com/14281621/187034568-7c44bc3c-52ec-4954-9df0-9766dd313e73.png)

The install size appears to have changed significantly between the versions.

**Comment by Finii** [comment]
Sorry to hear of and see your problem with 2.2.1.

The right image looks like it does mix fonts that should not be used together.

The JetBrains got another variant now, `JetBrains Mono Nerd Font` and `JetBrains Mono NL Nerd Font`:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono

The individual font files look fine at first glance.
The font family naming is buggy, but that has already been so in 2.1.0

Some questions that would help reproducing
* Is the effect also visible in `gnome-terminal`, or `tilix`, or `kitty` (spares me learning `alacritty`)?
* Did you reboot (I know usually not needed)?
* Can you share the `alacritty` configuration (screenshot or something)?
* Do you have the 'regular' Jet Brains Mono installed in parallel?
* Would you have time and like to test a new set of `JetBrainsMono NF` when I prepare one?

This AUR installs 128 font files. With the broken family naming this can be problematic.

**Comment by simonwiles** [comment]
I had the same issue with `konsole` (`nerd-fonts-jetbrains-mono` installed from the AUR on Arch). Fwiw the `PKGBUILD` from the AUR installs 64 fonts for me, including the new NL variant (which is very welcome, thanks!).

Noodling around rolling back to `2.1.0` and then reinstalling `2.2.1` for testing purposes, I am no longer able to reproduce the issue.  I think it was caused by a faulty post-install script that the AUR maintainer has now removed (as of 2 hours ago, commit `ab7a714f`).

**Comment by liamtimms** [comment]
@simonwiles I just tested with the new commit and the issue is still present after a reboot. 

@Finii can you explain the "font family naming is buggy" a little bit more? 


> Is the effect also visible in gnome-terminal, or tilix, or kitty (spares me learning alacritty)?

It seems to be ok in gnome-terminal:

![image](https://user-images.githubusercontent.com/14281621/187047345-8b548fbc-8c59-458a-bffb-ab73f2cbdea0.png)

Yet, gnome-terminal also doesn't let me pick the medium variant, which I have found much more readable. I know that Alacritty does not support ligatures and now see that "NL" stands for "no ligatures"; if ligatures handling has changed that might be part of the issue, but specifying `jetbrainsmononl` seems not actually to be affecting it. Possibly this is due to the buggy behavior around picking the font family you mentioned. I can file something on the alacritty bug tracker if that's more appropriate but I am keeping the nerd front downgraded in the meantime. 

> Did you reboot (I know usually not needed)?

Yep. 

> Can you share the alacritty configuration (screenshot or something)?

<details><summary>click for font config</summary>
<p>

```yaml
# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    #
    #family: monospace
    # family: source code pro semibold
    family: jetbrainsmono medium nerd font 

    # The `style` can be specified to pick a specific face.
    #style: Regular

  # Bold font face
  bold:
    # Font family
    #
    family: jetbrainsmono Extrabold nerd font
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: source code pro

    # The `style` can be specified to pick a specific face.
    style: Extrabold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: source code pro semibold

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    family: jetbrainsmono Extrabold Italic nerd font
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: monospace

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 12.5
```

</p>
</details>


> Do you have the 'regular' Jet Brains Mono installed in parallel?

Nope, only the nerd font versions. 


> Would you have time and like to test a new set of JetBrainsMono NF when I prepare one?`

Sure. 

> This AUR installs 128 font files. With the broken family naming this can be problematic.

Should the NL fonts be separated into their own package?
