### ISSUE TITLE
Iosevka doesn't show while FiraCode works well

### ISSUE THREAD

**Issue by crispgm** [ryanoasis/nerd-fonts#953]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior: I am using Iosevka Nerd Font, and the symbols not show. While I tried FiraCode Nerd Font, it works pretty good.

Expected behavior: Iosevka Nerd Font works well

Example symbols:  

#### 🔧 Your Setup

Font: Iosevka Nerd Font
Terminal: Alacritty
OS: macOS

#### ★ Screenshots (Optional)

```yaml
font:
  normal:
    family: 'Iosevka Nerd Font'
    style: Regular
```
<img width="344" alt="Snipaste_2022-10-05_02-11-15" src="https://user-images.githubusercontent.com/1425636/193894404-e9c2061f-03a4-4575-beb3-1a15b63048df.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/1425636/193895206-ee839ff7-8d46-419d-9ea2-3d04807ab5ff.png">

```yaml
font:
  normal:
    family: 'FiraCode Nerd Font'
    style: Regular
```
<img width="433" alt="Snipaste_2022-10-05_02-11-49" src="https://user-images.githubusercontent.com/1425636/193894387-819aa5bc-be8c-467b-a2ae-3305c133456b.png">
